# Generated by Django 4.2.9 on 2024-01-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitch_management_app', '0002_alter_pitch_turf_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='weather',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
